### ISSUE TITLE
Make exports tree-shakable

### ISSUE THREAD

**Issue by bergos** [rdfjs-base/formats#13]
from #3

> I see that package got an ESM upgrade. But I'm concerned with the main module exports
> 
> ```js
> export default formats
> export {
>   JsonLdParser,
>   JsonLdSerializer,
>   N3Parser,
>   NTriplesSerializer,
>   RdfXmlParser
> }
> ```
> 
> It's a shame you export like this because this offers web apps no way to tree-shake a ton of dependencies, most of which will never be used. All of the parsers and serialisers are forced to import and bundle as soon as the formats-common package is itself imported

I haven't tried, but I would have expected that the `formats` object is not created at all if you only import the parsers and serializers. Together with the `@rdfjs/sink-map` package, one can create their custom formats package.

**Comment by tpluscode** [comment]
> I would have expected that the `formats` object is not created at all if you only import the parsers and serializers.

You mean when one would `import { JsonLdParser } from '@rdfjs/formats-common'`?

My concern is the opposite, with `import formats from '@rdfjs/formats-common'` which is the standard, and documented usage for this package. This would inevitably lead to all parsers and all serialisers being imported and instantiated, am I right?

**Comment by bergos** [comment]
> This would inevitably lead to all parsers and all serialisers being imported and instantiated, am I right?

You are right, but the priorities are works out-of-the-box with low complexity over bundle size. And if you load the parser/serializer on demand during a user interaction, the user experience could be worse. As there is no clear benefit and no blocker implementing it on the application side, I will close this issue.
