### ISSUE TITLE
Updating to v3 causes unhandled rejection

### ISSUE THREAD

**Issue by tpluscode** [rdfjs-base/formats#16]
This has been killing me. I have been trying to update this package in `barnard59-rdf` but something weird happens in one test which tests when `file-fetch` throws an exception. Mocha complains that `done` is called twice. 

I found that indeed, when the `ReadableError` emits an error it falls into a handler for uncaught errors

The PR: https://github.com/zazuko/barnard59-rdf/pull/35

Any ideas what is going on? I expect the problem may not be directly related to `formats-common` but the only way to mitigate this problem is by keeping it as `v2`.

**Comment by bergos** [comment]
Outdated, and no example to reproduce the error provided.
