### ISSUE TITLE
Lazy imports

### ISSUE THREAD

**Issue by tpluscode** [rdfjs-base/formats#3]
I would like this package to be more browser-friendly by making two changes:

1. Change to ES modules as the default format (I've been successfully using esm to keep seamless node support)
2. Dynamically load parsers/serialisers only when streams are imported. This browser apps will import `formats-common` as usual but individual parsers and serialisers will only be fetched when they are required

**Comment by tpluscode** [comment]
Hey @bergos. I see that package got an ESM upgrade. But I'm concerned with the main module exports

```js
export default formats
export {
  JsonLdParser,
  JsonLdSerializer,
  N3Parser,
  NTriplesSerializer,
  RdfXmlParser
}
```

It's a shame you export like this because this offers web apps no way to tree-shake a ton of dependencies, most of which will never be used. All of the parsers and serialisers are forced to import and bundle as soon as the formats-common package is itself imported

**Comment by bergos** [comment]
Let's not mix lazy loading and tree-shakable exports. I created a separate issue #13 for the second topic. Lazy loading will not be added to the package. Therefore, I will close this issue.
