### ISSUE TITLE
Update readable-stream

### ISSUE THREAD

**Issue by tpluscode** [rdfjs-base/formats#4]
Currently the different parser and serialiser packages refer to incompatible versions of readable-stream 2.x and 3.x

Here's `npm ls readable-stream --prod` from [alcaeus](https://github.com/wikibus/alcaeus)

```
alcaeus@1.0.0-alpha.16 /Users/tomaszpluskiewicz/projects/github/wikibus/heracles
├─┬ @rdfjs/formats-common@2.1.0
│ ├─┬ @rdfjs/parser-jsonld@1.2.0
│ │ ├─┬ concat-stream@1.6.2
│ │ │ └── readable-stream@2.3.7
│ │ └── readable-stream@2.3.7
│ ├─┬ @rdfjs/parser-n3@1.1.3
│ │ └── readable-stream@2.3.7
│ ├─┬ @rdfjs/serializer-jsonld@1.2.1
│ │ └── readable-stream@2.3.7
│ └─┬ @rdfjs/serializer-ntriples@1.0.3
│   └─┬ readable-to-readable@0.1.3
│     └── readable-stream@3.6.0  deduped
├─┬ rdf-dataset-indexed@0.4.0
│ └── readable-stream@3.6.0  deduped
├─┬ rdf-transform-triple-to-quad@1.0.2
│ └── readable-stream@3.6.0  deduped
└── readable-stream@3.6.0
```

I create this issue to track PRs which will update the dependencies' dependencies to have a single resolution of `readable-stream@^3`

**Comment by bergos** [comment]
All `@rdfjs` packages have been updated. Only `n3` still depends on 3.x of `readable-stream`. I opened an [issue](https://github.com/rdfjs/N3.js/issues/309) to publish a new release. Until there is a new release, it's possible to use `overrides` like [here](https://github.com/rdfjs-base/parser-n3/blob/master/package.json#L35-L37). As there is a workaround and an open issue in the `n3` package, I will close this issue.
